name: CI
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Unit Testing
        run: npm test -- --watch=false --browsers=ChromeHeadless

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1

     - name: Check if test report exists
        run: |
          if [ -f ./coverage/read-bible/index.html ]; then
            echo "Test report exists"
            echo "Attachments:"
            ls -lh ./coverage/read-bible/
          else
            echo "Test report does not exist"
            exit 1
          fi

      # 建立並設置郵件通知
      - name: Setup email notification
        uses: dawidd6/action-send-mail@v3.2.0
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          from: 's01059810@gmail.com'
          to: ${{ secrets.EMAIL_TO }}
          subject: ${{ secrets.EMAIL_SUBJECT }}
          body: ${{ secrets.EMAIL_BODY }}
          attach_files: |
            ./coverage/read-bible/index.html
