name: CI
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Unit Testing
        run: npm test -- --watch=false --browsers=ChromeHeadless

      - name: Run tests with coverage
        env:
          CI: true
        run: |
          npm run test -- --code-coverage 
          npm install -D istanbul-lib-coverage istanbul-reports istanbul-api
          npx nyc report --reporter=lcov
          export COVERAGE=$(npx nyc report --reporter=text-summary | grep 'All files' | awk '{print $NF}')
          echo "Coverage: $COVERAGE" >> coverage.txt

      - name: Compress coverage report
        run: zip -r coverage.zip coverage

      # 建立並設置郵件通知
      - name: Setup email notification
        uses: dawidd6/action-send-mail@v3.2.0
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          from: 's01059810@gmail.com'
          to: ${{ secrets.EMAIL_TO }}
          subject: ${{ secrets.EMAIL_SUBJECT }}
          body: ${{ secrets.EMAIL_BODY }}
          attachments: coverage.zip
