name: CI
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # 執行 unit test
      - run: npm test -- --watch=false --browsers=ChromeHeadless

      # 建立並設置郵件通知
      - name: Setup email notification
        uses: dawidd6/action-send-mail@v3.2.0
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          from: 's01059810@gmail.com'
          to: ${{ secrets.EMAIL_TO }}
          subject: ${{ secrets.EMAIL_SUBJECT }}
          body: ${{ secrets.EMAIL_BODY }}
