name: CI
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # 建立並設置郵件通知
      - name: Setup email notification
        uses: dawidd6/action-send-mail@v3.2.0
        with:
          server_address: smtp.gmail.com
          server_port: 587
          EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_TO: ${{ secrets.EMAIL_TO }}
          subject: ${{ secrets.EMAIL_SUBJECT }}
          body: ${{ secrets.EMAIL_BODY }}
          from_name: 'JenniferShih'

      # 發送郵件通知
      - name: Send email notification
        run: |
          echo "Sending email notification"
          cd code/sent-email
          python send_email.py
